### PR TITLE
always restore moved apps dir

### LINKED ISSUE #280: Updater breaks OC leaving apps empty
Commit 6c88f76b18f00935415eb4c7999ade5446dea07d breaks OC completely.
What happens:

- "apps" directory is moved to "__apps"
- empty "apps" dir is created
- updater runs (with empty apps dir)
- updater doesn't report updating apps
- "apps" stays empty
- "__apps" stays untouched

--> owncloud broken with empty "apps" dir

### PR DESCRIPTION
**Pull request by Phiber2000**
fixes #280
Makes sure, that apps dir is restored.
(didn't use finally block to keep compatibility with PHP <5.5)

### CODE REVIEW

File: src/Command/ExecuteCoreUpgradeScriptsCommand.php [hunk 1]
```diff
@@ -104,14 +104,14 @@ protected function execute(InputInterface $input, OutputInterface $output){
 				$fsHelper->move($oldSourcesDir . '/apps', $oldSourcesDir . '/__apps');
 				$fsHelper->mkdir($oldSourcesDir . '/apps');
 				$plain = $this->occRunner->run('upgrade');
-				$fsHelper->removeIfExists($oldSourcesDir . '/apps');
-				$fsHelper->move($oldSourcesDir . '/__apps', $oldSourcesDir . '/apps');
```
Comment (VicDeo) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: @Phiber2000 it would be better to leave these lines and copy them right after the line 110 (catch) because new exception is thrown in L112. The code after the catch clause will be never executed in this case

File: src/Command/ExecuteCoreUpgradeScriptsCommand.php [hunk 2]
```diff
@@ -104,14 +104,14 @@ protected function execute(InputInterface $input, OutputInterface $output){
...
 				$output->writeln($plain);
 			} catch (ProcessFailedException $e){
 				if ($e->getProcess()->getExitCode() != 3){
 					throw ($e);
```
Comment (VicDeo) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: here, the code in this method will not be executed due to this throw

Comment (Phiber2000) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: totally clear. Thank you!

File: src/Command/ExecuteCoreUpgradeScriptsCommand.php [hunk 3]
```diff
@@ -108,6 +108,8 @@ protected function execute(InputInterface $input, OutputInterface $output){
 				$fsHelper->move($oldSourcesDir . '/__apps', $oldSourcesDir . '/apps');
 				$output->writeln($plain);
 			} catch (ProcessFailedException $e){
+				$fsHelper->removeIfExists($oldSourcesDir . '/apps');
+				$fsHelper->move($oldSourcesDir . '/__apps', $oldSourcesDir . '/apps');
 				if ($e->getProcess()->getExitCode() != 3){
```
Comment (Phiber2000) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: Not sure, if that couldn't be executed twice...

File: src/Command/ExecuteCoreUpgradeScriptsCommand.php [hunk 4]
```diff
@@ -108,6 +108,8 @@ protected function execute(InputInterface $input, OutputInterface $output){
 				$fsHelper->move($oldSourcesDir . '/__apps', $oldSourcesDir . '/apps');
 				$output->writeln($plain);
 			} catch (ProcessFailedException $e){
+				$fsHelper->removeIfExists($oldSourcesDir . '/apps');
+				$fsHelper->move($oldSourcesDir . '/__apps', $oldSourcesDir . '/apps');
```
Comment (Phiber2000) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: Not sure, if that couldn't be executed twice...
Doesn't matter if it is - but better twice than never.

**Comment by Phiber2000** [comment]
Is it okay to merge? Backports requested?

File: src/Command/ExecuteCoreUpgradeScriptsCommand.php (hunk 4 above)
Comment (VicDeo) [inline src/Command/ExecuteCoreUpgradeScriptsCommand.php]: @Phiber2000 It will be executed twice in case move in the line 108 fails which is nearly impossible. So I think this is ok.

**Comment by VicDeo** [comment]
:+1:

**Comment by VicDeo** [comment]
@Phiber2000 yes, backport would be nice
